/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LicitacoesRouteImport } from './routes/licitacoes'
import { Route as ConcorrenciasRouteImport } from './routes/concorrencias'
import { Route as IndexRouteImport } from './routes/index'

const LicitacoesRoute = LicitacoesRouteImport.update({
  id: '/licitacoes',
  path: '/licitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcorrenciasRoute = ConcorrenciasRouteImport.update({
  id: '/concorrencias',
  path: '/concorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concorrencias': typeof ConcorrenciasRoute
  '/licitacoes': typeof LicitacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concorrencias': typeof ConcorrenciasRoute
  '/licitacoes': typeof LicitacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concorrencias': typeof ConcorrenciasRoute
  '/licitacoes': typeof LicitacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/concorrencias' | '/licitacoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/concorrencias' | '/licitacoes'
  id: '__root__' | '/' | '/concorrencias' | '/licitacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcorrenciasRoute: typeof ConcorrenciasRoute
  LicitacoesRoute: typeof LicitacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/licitacoes': {
      id: '/licitacoes'
      path: '/licitacoes'
      fullPath: '/licitacoes'
      preLoaderRoute: typeof LicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concorrencias': {
      id: '/concorrencias'
      path: '/concorrencias'
      fullPath: '/concorrencias'
      preLoaderRoute: typeof ConcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcorrenciasRoute: ConcorrenciasRoute,
  LicitacoesRoute: LicitacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
