/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AtestadosRouteImport } from './routes/atestados'
import { Route as IndexRouteImport } from './routes/index'

const AtestadosRoute = AtestadosRouteImport.update({
  id: '/atestados',
  path: '/atestados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atestados': typeof AtestadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atestados': typeof AtestadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atestados': typeof AtestadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atestados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atestados'
  id: '__root__' | '/' | '/atestados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtestadosRoute: typeof AtestadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/atestados': {
      id: '/atestados'
      path: '/atestados'
      fullPath: '/atestados'
      preLoaderRoute: typeof AtestadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtestadosRoute: AtestadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
