/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LicitacoesRouteImport } from './routes/licitacoes'
import { Route as ConcorrenciasRouteImport } from './routes/concorrencias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtestadosIndexRouteImport } from './routes/atestados/index'
import { Route as AtestadosPlanilhaRouteImport } from './routes/atestados/planilha'
import { Route as AtestadosNovoRouteImport } from './routes/atestados/novo'

const LicitacoesRoute = LicitacoesRouteImport.update({
  id: '/licitacoes',
  path: '/licitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcorrenciasRoute = ConcorrenciasRouteImport.update({
  id: '/concorrencias',
  path: '/concorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtestadosIndexRoute = AtestadosIndexRouteImport.update({
  id: '/atestados/',
  path: '/atestados/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtestadosPlanilhaRoute = AtestadosPlanilhaRouteImport.update({
  id: '/atestados/planilha',
  path: '/atestados/planilha',
  getParentRoute: () => rootRouteImport,
} as any)
const AtestadosNovoRoute = AtestadosNovoRouteImport.update({
  id: '/atestados/novo',
  path: '/atestados/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concorrencias': typeof ConcorrenciasRoute
  '/licitacoes': typeof LicitacoesRoute
  '/atestados/novo': typeof AtestadosNovoRoute
  '/atestados/planilha': typeof AtestadosPlanilhaRoute
  '/atestados/': typeof AtestadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concorrencias': typeof ConcorrenciasRoute
  '/licitacoes': typeof LicitacoesRoute
  '/atestados/novo': typeof AtestadosNovoRoute
  '/atestados/planilha': typeof AtestadosPlanilhaRoute
  '/atestados': typeof AtestadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concorrencias': typeof ConcorrenciasRoute
  '/licitacoes': typeof LicitacoesRoute
  '/atestados/novo': typeof AtestadosNovoRoute
  '/atestados/planilha': typeof AtestadosPlanilhaRoute
  '/atestados/': typeof AtestadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concorrencias'
    | '/licitacoes'
    | '/atestados/novo'
    | '/atestados/planilha'
    | '/atestados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concorrencias'
    | '/licitacoes'
    | '/atestados/novo'
    | '/atestados/planilha'
    | '/atestados'
  id:
    | '__root__'
    | '/'
    | '/concorrencias'
    | '/licitacoes'
    | '/atestados/novo'
    | '/atestados/planilha'
    | '/atestados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcorrenciasRoute: typeof ConcorrenciasRoute
  LicitacoesRoute: typeof LicitacoesRoute
  AtestadosNovoRoute: typeof AtestadosNovoRoute
  AtestadosPlanilhaRoute: typeof AtestadosPlanilhaRoute
  AtestadosIndexRoute: typeof AtestadosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/licitacoes': {
      id: '/licitacoes'
      path: '/licitacoes'
      fullPath: '/licitacoes'
      preLoaderRoute: typeof LicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concorrencias': {
      id: '/concorrencias'
      path: '/concorrencias'
      fullPath: '/concorrencias'
      preLoaderRoute: typeof ConcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atestados/': {
      id: '/atestados/'
      path: '/atestados'
      fullPath: '/atestados/'
      preLoaderRoute: typeof AtestadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atestados/planilha': {
      id: '/atestados/planilha'
      path: '/atestados/planilha'
      fullPath: '/atestados/planilha'
      preLoaderRoute: typeof AtestadosPlanilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atestados/novo': {
      id: '/atestados/novo'
      path: '/atestados/novo'
      fullPath: '/atestados/novo'
      preLoaderRoute: typeof AtestadosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcorrenciasRoute: ConcorrenciasRoute,
  LicitacoesRoute: LicitacoesRoute,
  AtestadosNovoRoute: AtestadosNovoRoute,
  AtestadosPlanilhaRoute: AtestadosPlanilhaRoute,
  AtestadosIndexRoute: AtestadosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
